### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kka-na** [kka-na/vacs#2]
- [x] DropAlerting Sound 
- [x] DropWarning 종류 알리기
- [x] State Alerting이랑 Take Over Request Alerting 구분하기
- [x] DropWarning 5초 후에 Drop 꺼지게
